<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>PersistentWorkflows.EntityFrameworkCore</PackageId>
        <EnablePackageValidation>true</EnablePackageValidation>
        <PackageValidationBaselineVersion>0.1.0-preview.2</PackageValidationBaselineVersion>
		<Description>Relational EF Core persistence operations for durable .NET workflows.</Description>
	</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersistentWorkflows.Abstractions\PersistentWorkflows.Abstractions.csproj" />
    <ProjectReference Include="..\PersistentWorkflows.Core\PersistentWorkflows.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
  </ItemGroup>

</Project>
